import catalogData from "@/data/catalog.json";

/*
 * The product catalog.
 *
 * src/data/catalog.json is generated by scripts/build-catalog.mjs and committed,
 * so the statically generated pages pick up current data on every Vercel
 * rebuild. It is keyed by ASIN and is the ONLY description of a product the
 * site has — title, photo, affiliate URL, price, rating.
 *
 * Products are addressed by ASIN, never by display name. The previous design
 * matched on name substrings, so getProductLink("Teton Sports Celsius Regular")
 * resolved by finding the key "Teton Sports" — two products sharing a brand
 * word collided silently, and editing a heading could repoint a link. An ASIN
 * either resolves or visibly does not.
 *
 * THE RULE: a price or rating renders ONLY when it comes from this file and is
 * recent. There is no fallback to the figure an article was written with.
 *
 * That rule exists because the fallback actively lied. A sleeping bag whose
 * spotlight card said "$34.99" was $94.99 on Amazon — the card rendered a
 * hardcoded string while the grid two inches below it rendered $94.99 from this
 * file, so the same page quoted two different prices for the same product.
 * Showing no number is always better than showing a wrong one: it costs a
 * click, while a wrong price costs trust and breaches the Associates agreement,
 * which forbids presenting non-API prices as current.
 *
 * Amazon's own API is not an option here: PA-API shut down 2026-05-15 and the
 * Creators API that replaced it requires 10 qualified sales in the trailing 30
 * days. Revisit this the moment the account clears that bar — it is the only
 * fully compliant source of Product Advertising Content.
 */
export type CatalogProduct = {
  asin: string;
  title: string;
  url: string;
  image: string | null;
  price: string | null;
  priceValue: number | null;
  rating: number | null;
  ratingsTotal: number | null;
  priceAsOf: string | null;
  verifiedAt: string | null;
};
const CATALOG = (catalogData as { products: Record<string, CatalogProduct> }).products ?? {};

/* Amazon prices move constantly, so a figure we last confirmed weeks ago is not
 * evidence of anything. Past this age we stop asserting a number at all. Pages
 * are statically generated and the price cron rebuilds daily, so this is
 * re-evaluated far more often than the window itself.
 *
 * This window must stay comfortably WIDER than the refresh interval in
 * scripts/refresh-prices.mjs (PRICE_STALE_HOURS, 120h). When the two are equal
 * every price becomes undisplayable at the exact moment it becomes eligible for
 * refresh, so any hiccup in the cron blanks prices site-wide. 10 days against a
 * 5-day refresh leaves a full refresh cycle of slack. */
export const PRICE_MAX_AGE_MS = 10 * 24 * 60 * 60 * 1000;

/** Look up a product by bare ASIN or by any Amazon /dp/ URL. */
export function productFor(ref?: string | null): CatalogProduct | null {
  if (!ref) return null;
  const asin = /^B[0-9A-Z]{9}$/.test(ref) ? ref : ref.match(/\/dp\/(B[0-9A-Z]{9})/)?.[1];
  return asin ? (CATALOG[asin] ?? null) : null;
}

/** The product only when its price is recent enough to quote. */
export function withLivePrice(p: CatalogProduct | null): CatalogProduct | null {
  if (!p?.price || !p.priceAsOf) return null;
  return Date.now() - Date.parse(p.priceAsOf) > PRICE_MAX_AGE_MS ? null : p;
}

/** What to show when we cannot stand behind a number. */
export const CHECK_PRICE = "Check price";

/** Newest priceAsOf among the given product refs, or null if none are priced. */
export function newestAsOf(refs: Array<string | undefined>): string | null {
  const dates = refs
    .map((r) => withLivePrice(productFor(r))?.priceAsOf)
    .filter(Boolean) as string[];
  return dates.length ? dates.sort().at(-1)! : null;
}
