#!/usr/bin/env node
/**
 * Generate src/data/catalog.json — the one record per product the site renders.
 *
 *   node scripts/build-catalog.mjs
 *
 * Inputs (both already maintained):
 *   state/asin-cache.json        pipeline truth: verdicts, titles, prices, ratings
 *   src/data/product-images.json curated ASIN -> photo URL
 *
 * Output: catalog.json, keyed by ASIN. Nothing else in the site describes a
 * product, and every field a page can render comes from here.
 *
 * WHY ASIN AND NOT NAME: the previous design matched products by substring on
 * their display name — getProductLink("Teton Sports Celsius Regular") worked by
 * finding the key "Teton Sports". Two products sharing a brand word collided
 * silently, and any copy edit to a heading could repoint a link. An ASIN is the
 * product's actual identity, so a lookup either resolves or visibly does not.
 *
 * Separation of concerns is deliberate: state/asin-cache.json is pipeline
 * bookkeeping that six scripts write to, while catalog.json is published data
 * imported at build time. Same split as specs/ versus src/data/articles.ts.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const ROOT = new URL("..", import.meta.url).pathname;
const AFFILIATE_TAG = "camprally-20";

const cache = JSON.parse(readFileSync(`${ROOT}state/asin-cache.json`, "utf8")).entries ?? {};
const images = JSON.parse(readFileSync(`${ROOT}src/data/product-images.json`, "utf8")).images ?? {};

/* One photo cannot be two products. The name-keyed map this replaced had the
 * Coleman Sundome's photo attached to a Klymit sleeping pad, so a grid of
 * "compared" products showed a tent where the pad should be. Refuse the image
 * rather than guess which ASIN owns it — an icon tile is honest, a photo of the
 * wrong product is not. */
const seen = new Map();
const contested = new Set();
for (const [asin, url] of Object.entries(images)) {
  if (seen.has(url)) {
    contested.add(url);
    console.warn(`  duplicate image: ${asin} and ${seen.get(url)} share a photo — dropping both`);
  }
  seen.set(url, asin);
}

const products = {};
for (const [asin, e] of Object.entries(cache)) {
  // A product we have never confirmed resolves is not publishable. DEAD entries
  // are kept in the cache on purpose (so we stop re-checking them) but must
  // never reach a page.
  if (e.verdict === "DEAD") continue;

  products[asin] = {
    asin,
    title: e.title ?? "",
    url: `https://www.amazon.com/dp/${asin}?tag=${AFFILIATE_TAG}`,
    image: contested.has(images[asin]) ? null : (images[asin] ?? null),
    price: e.price ?? null,
    priceValue: e.priceValue ?? null,
    rating: e.rating ?? null,
    ratingsTotal: e.ratingsTotal ?? null,
    priceAsOf: e.priceCheckedAt ?? null,
    verifiedAt: e.checkedAt ?? null,
  };
}

const payload = {
  generatedAt: new Date().toISOString(),
  note: "Generated by scripts/build-catalog.mjs from state/asin-cache.json + src/data/product-images.json. Do not edit by hand.",
  products,
};

mkdirSync(`${ROOT}src/data`, { recursive: true });
writeFileSync(`${ROOT}src/data/catalog.json`, JSON.stringify(payload, null, 2) + "\n");

const withPrice = Object.values(products).filter((p) => p.price).length;
const withImage = Object.values(products).filter((p) => p.image).length;
console.log(
  `catalog: ${Object.keys(products).length} products · ` +
  `${withPrice} priced · ${withImage} with photos`,
);
