import HERO_ALT from "@/data/hero-alt.json";

/*
 * Hero photograph per article slug.
 *
 * Lifted out of the article template so the home page and blog index can render
 * the same image on their cards. Cards without a photo were the single biggest
 * reason the site read as a blog rather than a gear store, and the pictures
 * already existed — they were just locked inside the article route.
 *
 * Surfacing them exposed two problems that had been invisible while the map was
 * only ever read one article at a time:
 *
 *   1. Three URLs 404'd (headlamps, rain gear, water filtration). On the
 *      article page that produced a dark band nobody looked twice at; on a card
 *      it is an empty grey tile in the middle of a grid.
 *   2. Eighteen of the 24 entries shared a photo with at least one other
 *      article, and three more slugs were missing entirely and fell through to
 *      `default`. A category listing rendered the same marshmallow picture on
 *      two adjacent cards.
 *
 * Every slug below now has its own topical photograph. All URLs were verified
 * with a request and reviewed as contact sheets before being assigned — an
 * images.unsplash.com URL returns 200 for essentially any well-formed photo id,
 * so "it resolves" is not evidence that it shows what you think it shows.
 *
 * KEEP THESE UNIQUE. If you add an article, add a hero with it.
 */
export const HERO_IMAGES: Record<string, string> = {
  // ── Shelter ──────────────────────────────────────────────────────────────
  "best-budget-tents-under-100":          "https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=1200&q=80",

  // ── Sleep ────────────────────────────────────────────────────────────────

  // ── Cooking & water ──────────────────────────────────────────────────────

  // ── Clothing & footwear ──────────────────────────────────────────────────
  "best-hiking-boots-camping-under-100": "https://images.unsplash.com/photo-1606036525923-525fa3b35465?w=1200&q=80",

  // ── Tools, lighting & navigation ─────────────────────────────────────────

  // ── Camp comfort ─────────────────────────────────────────────────────────
  "best-camping-chairs-tailgating":      "https://images.unsplash.com/photo-1605401923238-b45d25aaecc8?w=1200&q=80",
  "best-camping-coolers-under-100":      "https://images.unsplash.com/photo-1604353624377-8f8f7d9a5dde?w=1200&q=80",
  "best-portable-camping-fans":          "https://images.unsplash.com/photo-1626077414855-6dfb9286c109?w=1200&q=80",
  "budget-camping-accessories-under-20": "/images/heroes/budget-camping-accessories-under-20.jpg",

  // ── Safety ───────────────────────────────────────────────────────────────
  "best-camping-first-aid-kits-under-50": "/images/heroes/best-camping-first-aid-kits-under-50.jpg",

  // ── Tips & planning ──────────────────────────────────────────────────────
  "how-to-camp-in-hot-weather":     "https://images.unsplash.com/photo-1573111651692-39ec7f38fec9?w=1200&q=80",
  /* Generated by write-article.mjs via MiniMax image-01 and committed to the
   * repo — the only locally hosted hero so far. New articles get one of these
   * automatically; the Unsplash URLs above are the pre-generator backlog. */

  "how-to-camp-in-rain": "/images/heroes/how-to-camp-in-rain.jpg",
  "camping-fire-starting-guide": "/images/heroes/camping-fire-starting-guide.jpg",
  "dispersed-camping-beginners-guide": "/images/heroes/dispersed-camping-beginners-guide.jpg",
  "camping-meal-plans-budget-50": "/images/heroes/camping-meal-plans-budget-50.jpg",
  "best-portable-power-station-camping-under-200": "/images/heroes/best-portable-power-station-camping-under-200.jpg",
  "best-camp-kitchen-organization": "/images/heroes/best-camp-kitchen-organization.jpg",
  "camping-with-dogs-checklist": "/images/heroes/camping-with-dogs-checklist.jpg",
  "best-camping-tarp-under-30": "/images/heroes/best-camping-tarp-under-30.jpg",
  "best-budget-trekking-poles": "/images/heroes/best-budget-trekking-poles.jpg",
  "memorial-day-camping-checklist-2026": "/images/heroes/memorial-day-camping-checklist-2026.jpg",
  "camping-bug-tick-prevention-spring": "/images/heroes/camping-bug-tick-prevention-spring.jpg",
  "labor-day-camping-weekend-guide": "/images/heroes/labor-day-camping-weekend-guide.jpg",
  "fall-camping-gear-essentials": "/images/heroes/fall-camping-gear-essentials.jpg",
  "best-camping-blankets-under-40": "/images/heroes/best-camping-blankets-under-40.jpg",
  "how-to-stay-warm-camping-cold-nights": "/images/heroes/how-to-stay-warm-camping-cold-nights.jpg",
  "best-budget-hiking-backpacks-under-100": "/images/heroes/best-budget-hiking-backpacks-under-100.jpg",
  "best-camping-lanterns-under-30": "/images/heroes/best-camping-lanterns-under-30.jpg",
  "best-camping-coffee-makers-under-40": "/images/heroes/best-camping-coffee-makers-under-40.jpg",
  "camping-with-kids-first-trip": "/images/heroes/camping-with-kids-first-trip.jpg",
  "best-camping-socks": "/images/heroes/best-camping-socks.jpg",
  "leaf-peeping-camping-destinations": "/images/heroes/leaf-peeping-camping-destinations.jpg",
  "best-4-season-tents-under-300": "/images/heroes/best-4-season-tents-under-300.jpg",
  "best-sleeping-bag-liners-camping": "/images/heroes/best-sleeping-bag-liners-camping.jpg",
  "best-budget-camping-cots": "/images/heroes/best-budget-camping-cots.jpg",
  "budget-camping-cookware-that-works": "/images/heroes/budget-camping-cookware-that-works.jpg",
  "best-budget-sleeping-pads-under-50": "/images/heroes/best-budget-sleeping-pads-under-50.jpg",
  "best-cheap-camping-tables": "/images/heroes/best-cheap-camping-tables.jpg",
  "budget-portable-camping-stoves-compared": "/images/heroes/budget-portable-camping-stoves-compared.jpg",
  "affordable-rain-gear-camping": "/images/heroes/affordable-rain-gear-camping.jpg",
  "budget-camp-chairs-that-last": "/images/heroes/budget-camp-chairs-that-last.jpg",
  "best-budget-camping-knife": "/images/heroes/best-budget-camping-knife.jpg",
  "best-budget-sleeping-bags-cold-weather": "/images/heroes/best-budget-sleeping-bags-cold-weather.jpg",
  "best-time-year-camp-free": "/images/heroes/best-time-year-camp-free.jpg",
  "how-to-start-camping-no-gear": "/images/heroes/how-to-start-camping-no-gear.jpg",
  "best-budget-multitool-camping": "/images/heroes/best-budget-multitool-camping.jpg",
  "affordable-headlamps-camping": "/images/heroes/affordable-headlamps-camping.jpg",
  "affordable-water-filtration-camping": "/images/heroes/affordable-water-filtration-camping.jpg",
  "best-budget-gps-compass-hiking": "/images/heroes/best-budget-gps-compass-hiking.jpg",
  "how-to-pack-light-camping": "/images/heroes/how-to-pack-light-camping.jpg",
  "how-to-find-free-campsites": "/images/heroes/how-to-find-free-campsites.jpg",
  "budget-camping-hacks-that-work": "/images/heroes/budget-camping-hacks-that-work.jpg",
  "cheapest-camping-setup-for-beginners": "/images/heroes/cheapest-camping-setup-for-beginners.jpg",
  "best-camping-hammocks-under-50": "/images/heroes/best-camping-hammocks-under-50.jpg",
  default: "https://images.unsplash.com/photo-1598507690808-57594afea85f?w=1200&q=80",
};

export function getHeroImage(slug: string): string {
  return HERO_IMAGES[slug] || HERO_IMAGES.default;
}

/**
 * Alt text for a hero, written by actually looking at the image.
 *
 * Generated by scripts/backfill-hero-alt.mjs through the `vision` role and
 * stored beside this file rather than inline, because it is machine-written
 * data regenerated in bulk and inlining it would make every rerun a large
 * hand-reviewed diff of this map.
 *
 * RETURNS "" WHEN THERE IS NO ENTRY, AND THAT IS DELIBERATE. An unknown image
 * gets an empty alt, which marks it decorative and makes a screen reader skip
 * it. The alternative — falling back to the article title — is the failure this
 * whole field exists to avoid: alt text that restates the H1 beside it is read
 * aloud twice and tells an image crawler nothing new. Silence beats noise.
 */
export function getHeroAlt(slug: string): string {
  return (HERO_ALT as Record<string, string>)[slug] ?? "";
}
